app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    TextAreaField,

)
from wtforms.validators import Length


class ProfileForm(FlaskForm):
    first_name = StringField("First Name")
    last_name = StringField("Last Name")
    linkedin_url = StringField('Linkedin')
    facebook_url = StringField('Facebook')
    bio = TextAreaField('About me', validators=[Length(min=0, max=200)])
    submit = SubmitField('Submit')

app/user/__init__.py
from pathlib import Path

from flask import Blueprint

import config
from .. import db
from ..models import User
import pandas as pd

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.cli.command('extract_users')
def extract_users():
    user_data = []
    users_info = db.session.query(User).all()
    for user in users_info:
        user_data.append(
            {
                'UserName': user.username,
                'Email': user.email,
                'FullName': user.profile.fullname,
                'PostCount': user.posts.count()
            }
        )
    df = pd.DataFrame(user_data, columns=['UserName', 'Email', 'FullName', 'PostCount'])
    df.to_csv(Path(config.Config.BASEDIR) / 'users.csv')


from . import routes  # noqa.

app/user/routes.py
from flask_login import login_required, current_user
from .forms import ProfileForm
from app.user import bp
from flask import render_template, flash, redirect, url_for, request
from .. import db
from ..models import User, Post
from ..post.forms import PostForm


@bp.route('/blog')
@login_required
def blog():
    form = PostForm()
    posts = (
        db.session.query(Post)
        .filter(
            Post.author_id == current_user.id
        )
        .order_by(Post.created_at.desc())
        .all()
    )
    return render_template('user/blog.html', posts=posts, form=form)


@bp.route('/profile/<string:username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    user = db.session.query(User).filter(User.username == username).first_or_404()
    form = ProfileForm()
    if form.validate_on_submit():
        user.profile.first_name = form.first_name.data
        user.profile.last_name = form.last_name.data
        user.profile.linkedIn_url = form.linkedin_url.data
        user.profile.facebook_url = form.facebook_url.data
        user.profile.bio = form.bio.data
        db.session.commit()
        flash('Your profile has been saved', category='success')
        return redirect(url_for('user.profile', username=user.username))
    elif request.method == 'GET':
        form.first_name.data = user.profile.first_name
        form.last_name.data = user.profile.last_name
        form.linkedin_url.data = user.profile.linkedIn_url
        form.facebook_url.data = user.profile.facebook_url
        form.bio.data = user.profile.bio
    return render_template('user/profile.html', title='Profile', form=form, user=user)


@bp.route('/user/<username>/follow', methods=['POST'])
@login_required
def follow_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        flash(f'You have already following {username}', category='warning')
    elif user is None:
        flash(f'Something went wrong, {username} not found', category='error')
    elif user != current_user:
        current_user.follow(user)
        flash(f'You are now following {username}.', 'success')
    else:
        flash('You cannot follow yourself.', 'danger')
    return redirect(url_for('user.profile', username=user.username))


@bp.route('/user/<username>/unfollow', methods=['POST'])
@login_required
def unfollow_user(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user != current_user:
        current_user.unfollow(user)
        flash(f'You have unfollowed {username}.', 'success')
    else:
        flash('You cannot unfollow yourself.', 'danger')
    return redirect(url_for('user.profile', username=user.username))

app/templates/user/blog.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        {% for post in posts %}
        {% include '_post.html' %}
        {% endfor %}
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Create a new post</h5>
                <form method="post" action="{{ url_for('post.create_post') }}" novalidate>
                    {{ form.csrf_token }}
                    <div class="form-group">
                        <label for="title">Title</label>
                        {{ form.post_title(class='form-control', id='title', placeholder='Enter title') }}
                    </div>
                    <div class="form-group">
                        <label for="content">Content</label>
                        {{ form.post_content(class='form-control', id='content', placeholder='Enter content') }}
                    </div>
                    <button type="submit" class="btn btn-primary">Create post</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="mb-4">Profile</h1>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ user.avatar(128) }}" class="img-thumbnail mb-3" alt="">
            <div>
                <h5>{{ user.username }}</h5>
                <p class="text-muted">{{ user.email }}</p>
            </div>
            <p class="small">Last seen: {{ user.profile.last_seen.strftime('%Y-%m-%d %H:%M:%S') }}</p>
        </div>
        {% if user != current_user %}
        {% if not current_user.is_following(user) %}
        <form method="post" action="{{ url_for('user.follow_user', username=user.username) }}">
            {{ form.csrf_token }}
            <button type="submit" class="btn btn-primary">Follow</button>
        </form>
        {% else %}
        <form method="post" action="{{ url_for('user.unfollow_user', username=user.username) }}">
            {{ form.csrf_token }}
            <button type="submit" class="btn btn-primary">Unfollow</button>
        </form>
        {% endif %}
        {% endif %}
        <div class="col-md-4">
            <h5>Followers</h5>
            <ul>
                {% for following in user.get_following() %}
                <li>{{ following.username }}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="col-md-4">
            <h5>Following</h5>
            <ul>
                {% for follower in user.get_followers() %}
                <li>{{ follower.username }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-8">
            {% if user == current_user %}
            <form method="post" action="{{ url_for('user.profile', username=user.username) }}">
                {{ form.csrf_token }}
                <div class="form-group row">
                    <label for="inputFirstName" class="col-sm-2 col-form-label">First Name</label>
                    <div class="col-sm-10">
                        {{ form.first_name(class="form-control", id="inputFirstName") }}
                        {% for error in form.first_name.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputLastName" class="col-sm-2 col-form-label">Last Name</label>
                    <div class="col-sm-10">
                        {{ form.last_name(class="form-control", id="inputLastName") }}
                        {% for error in form.last_name.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputFacebook" class="col-sm-2 col-form-label">Facebook</label>
                    <div class="col-sm-10">
                        {{ form.facebook_url(class="form-control", id="inputFacebook") }}
                        {% for error in form.facebook_url.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputLinkedin" class="col-sm-2 col-form-label">LinkedIn</label>
                    <div class="col-sm-10">
                        {{ form.linkedin_url(class="form-control", id="inputLinkedin") }}
                        {% for error in form.linkedin_url.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputBio" class="col-sm-2 col-form-label">About Me</label>
                    <div class="col-sm-10">
                        {{ form.bio(class="form-control", id="inputBio") }}
                        {% for error in form.bio.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}