app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    post_title = StringField('Title', validators=[DataRequired(), Length(min=2, max=200)])
    post_content = TextAreaField('Content', validators=[DataRequired(), Length(min=1, max=5000)])
    submit = SubmitField('Create Post')

app/post/__init__.py
from pathlib import Path

import click
from flask import Blueprint
import pandas as pd

import config
from .. import db
from ..models import Post, User

bp = Blueprint('post', __name__, url_prefix='/post')


@bp.cli.command('extract_posts')
@click.argument('user_id', type=int)
def extract_posts(user_id):
    post_info = []
    user_name = db.session.query(User.username).filter(User.id == user_id).scalar()
    if user_name:
        posts = db.session.query(Post).filter(Post.author_id == user_id).all()
        for post in posts:
            title = post.title
            likes = len(post.likes)
            dislikes = len(post.dislikes)
            created = post.created_at
            post_info.append(
                {
                    'PostTitle': title,
                    'Likes': likes,
                    'Dislikes': dislikes,
                    'CreatedAT': created
                }
            )
        df = pd.DataFrame(post_info, columns=['PostTitle', 'Likes', 'Dislikes', 'CreatedAT'])
        df.to_csv(Path(config.Config.BASEDIR) / f'{user_name}_posts_info.csv')
    else:
        print('Error! User didnt found')


from . import routes  # noqa

app/post/routes.py
from os import abort
from flask import request, flash, redirect, url_for, render_template
from flask_login import login_required, current_user
from app import db
from app.models import Post, Like, Dislike
from app.post import bp
from app.post.forms import PostForm


@bp.route('/create', methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(title=form.post_title.data, content=form.post_content.data, author=current_user)
            db.session.add(post)
            db.session.commit()
            flash('Excellent, your post has been created', category='success')
        else:
            title = form.post_title.data
            if not title or len(title) < 2:
                flash('Sorry, title must be at least two characters long', category='error')
        return redirect(url_for('user.blog', user=current_user))
    return render_template('user/blog.html', form=form, title='Create post')


@bp.route('/<int:post_id>/like', methods=['GET', 'POST'])
@login_required
def like(post_id):
    post = Post.query.get_or_404(post_id)
    post_dislike = Dislike.query.filter_by(user=current_user, post=post).first()
    post_like = Like(user=current_user, post=post)
    if Like.query.filter_by(user=current_user, post=post).count() > 0:
        flash('Sorry, but you already like this post😎', category='warning')
    elif post_dislike:
        db.session.delete(post_dislike)
        db.session.commit()
        db.session.add(post_like)
        db.session.commit()
        flash('Thanks, i knew this post get likes🤪', category='success')
    else:
        db.session.add(post_like)
        db.session.commit()
        flash('Thanks, i knew this post get likes🤪', category='success')
    return redirect(request.referrer)


@bp.route('/<int:post_id>/dislike', methods=['GET', 'POST'])
def dislike(post_id):
    post = Post.query.get_or_404(post_id)
    post_like = Like.query.filter_by(user=current_user, post=post).first()
    post_dislike = Dislike(user=current_user, post=post)
    if Dislike.query.filter_by(user=current_user, post=post).count() > 0:
        flash('Sorry, but you already dislike this post😪', category='warning')
    elif post_like:
        db.session.delete(post_like)
        db.session.commit()
        db.session.add(post_dislike)
        db.session.commit()
        flash('What?are you seriously?my post is magnificent', category='success')
    else:
        db.session.add(post_dislike)
        db.session.commit()
        flash('What?are you seriously?my post is magnificent', category='success')

    return redirect(request.referrer)


@bp.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    post_delete = Post.query.get_or_404(post_id)
    if post_delete.author != current_user:
        abort(403)
    else:
        db.session.delete(post_delete)
        db.session.commit()
        flash('Your post has been deleted', category='success')
    return redirect(url_for('user.blog'))

app/templates/_post.html
<div class="card mb-3">
    <div class="card-body d-flex align-items-center">
        <div>
            <h5 class="card-title">{{ post.title }}</h5>

            <p class="card-text">{{ post.content }}</p>
            <p class="card-text"><small class="text-muted">{{ post.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </p>
        </div>
    </div>
    <div class="card-footer">
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a id="post_like" href="{{ url_for('post.like', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                    <i class="fas fa-thumbs-up"></i>
                    {{ post.likes|length }}
                </a>
                <a id="post_dislike" href="{{ url_for('post.dislike', post_id=post.id) }}" class="btn btn-sm btn-outline-primary">
                    <i class="fas fa-thumbs-down"></i> {{ post.dislikes|length }}
                </a>
                {% if request.path == url_for('user.blog') %}
                    {% if current_user == post.author %}
                        <a href="{{ url_for('post.delete', post_id=post.id) }}" class="btn btn-sm btn-outline-danger">
                            <i class="fas fa-trash-alt"></i> Delete
                        </a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="d-flex align-items-center">
                <a href="{{ url_for('user.profile', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(32) }}" class="rounded-circle mr-1">
                </a>
                <span>{{ post.author.username }}</span>
            </div>
        </div>
    </div>
</div>

app/templates/about.html
{% extends "base.html" %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>This page under construction</h1>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>
        {% block title %}
        {% if title %}
        {{ title }}
        {% else %}
        FalskAPP
        {% endif %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        .nav_link_color {
            color: white;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand nav_link_color" href="{{ url_for('main.index') }}">Flask Dev Network</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    {% if current_user.is_authenticated %}
                <li class="nav-item{% if active == 'index' %} active{% endif %}">
                    <a class="nav-link nav_link_color" href="{{ url_for('user.blog') }}">Blog</a>
                </li>
                <li class="nav-item{% if active == 'index' %} active{% endif %}">
                    <a class="nav-link nav_link_color"
                       href="{{ url_for('user.profile', username=current_user.username) }}">Profile</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link nav_link_color" href="{{ url_for('main.about') }}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-2">
                    {% if current_user.is_authenticated %}
                    <a id="logout_btn" class="nav-link nav_link_color" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link nav_link_color" href="{{ url_for('auth.login') }}">Login</a>
                    {% endif %}
                </li>
                {% if not current_user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="nav-link nav_link_color" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == "error" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% elif category == "success" %}
    <div class="alert alert-success">{{ message }}</div>
    {% elif category == "warning" %}
    <div class="alert alert-warning">{{ message }}</div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous">
</script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
{% endblock %}

app/templates/profile.html
<!DOCTYPE html>
<html lang="">
<head>
    <title>
        {% block title %}
        {% if title %}
        {{ title }}
        {% else %}
        WebDev
        {% endif %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<style>
    .nav_link_color {
        color: white;
    }
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <!--bg-dark-->
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('user.profile') }}">FlaskAPP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <!--                <li class="nav-item{% if active == 'index' %} active{% endif %}">-->
                    <!--                    <a class="nav-link nav_link_color" href="{{ url_for('main.index') }}">Home</a>-->
                    <!--                </li>-->
                <li class="nav-item">
                    <a class="nav-link nav_link_color" href="{{ url_for('user.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav_link_color" href="{{ url_for('user.edit_profile') }}">Edite Profile</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item me-2">
                    {% if current_user.is_authenticated %}
                    <a class="nav-link nav_link_color" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link nav_link_color" href="{{ url_for('auth.login') }}">Login</a>
                    {% endif %}
                </li>
                {% if not current_user.is_authenticated %}
                <li class="nav-item me-2">
                    <a class="nav-link nav_link_color" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == "error" %}
    <div class="alert alert-danger">{{ message }}</div>
    {% elif category == "success" %}
    <div class="alert alert-success">{{ message }}</div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}


    {% block content %}
    <ul>
        {% for user in users %}
        <li>{{ user.username }} - {{ user.email }}</li>
        {% endfor %}
    </ul>
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>